"""Amazon Bedrock adapter (Claude Haiku) for explanation only.

The model is never allowed to produce a number that is not already in the
JSON context we supply. That constraint lives in SYSTEM_PROMPT, and the
fallback path produces a purely templated answer from the same JSON so a
Bedrock outage cannot turn into an invented figure.
"""

from __future__ import annotations

import json
import logging
from functools import lru_cache
from typing import Any

from app.config import get_settings

logger = logging.getLogger(__name__)

SYSTEM_PROMPT = (
    "You are a risk explanation assistant. You MUST NOT invent, estimate, or "
    "calculate any numbers. You MUST only explain the structured data "
    "provided. Every number you mention must come from the supplied JSON. If "
    "asked for a number not in the data, say: I cannot confirm that from the "
    "available evidence."
)


class BedrockService:
    def __init__(self) -> None:
        self.settings = get_settings()
        self._client = None
        self.mode = "fallback"
        self._init_error: str | None = None
        if self.settings.bedrock_enabled:
            self._connect()
        else:
            self._init_error = "BEDROCK_ENABLED=false"

    def _connect(self) -> None:
        try:
            import boto3

            self._client = boto3.client(
                "bedrock-runtime", region_name=self.settings.aws_region
            )
            self.mode = "bedrock"
            logger.info("Bedrock client ready (%s)", self.settings.bedrock_model_id)
        except Exception as exc:
            self._client = None
            self.mode = "fallback"
            self._init_error = f"{type(exc).__name__}: {exc}"
            logger.warning("Bedrock unavailable, using templated fallback (%s)", exc)

    @property
    def status(self) -> dict[str, Any]:
        return {
            "mode": self.mode,
            "model_id": self.settings.bedrock_model_id,
            "error": self._init_error,
        }

    def explain(self, question: str, context: dict) -> dict[str, Any]:
        """Ask Haiku to explain `context`. Returns text plus the mode used."""
        payload = {
            "anthropic_version": "bedrock-2023-05-31",
            "max_tokens": self.settings.bedrock_max_tokens,
            "temperature": 0.0,
            "system": SYSTEM_PROMPT,
            "messages": [
                {
                    "role": "user",
                    "content": (
                        "Structured data (the only permitted source of numbers):\n"
                        f"{json.dumps(context, indent=2, default=str)}\n\n"
                        f"Question: {question}"
                    ),
                }
            ],
        }

        if self.mode == "bedrock" and self._client is not None:
            try:
                resp = self._client.invoke_model(
                    modelId=self.settings.bedrock_model_id,
                    body=json.dumps(payload),
                    contentType="application/json",
                    accept="application/json",
                )
                body = json.loads(resp["body"].read())
                blocks = body.get("content", [])
                text = "".join(
                    b.get("text", "") for b in blocks if b.get("type") == "text"
                ).strip()
                if text:
                    return {"answer": text, "mode": "bedrock"}
                logger.warning("Bedrock returned no text block, using fallback")
            except Exception as exc:
                logger.error("Bedrock invoke failed: %s", exc)

        return {"answer": _templated_answer(question, context), "mode": "fallback"}


def _templated_answer(question: str, context: dict) -> str:
    """Deterministic explanation built only from `context`. No model involved."""
    lines: list[str] = [
        "Bedrock is not reachable, so this is a templated explanation built "
        "directly from the computed data. No number below was generated by a "
        "language model.",
        "",
    ]

    selected = context.get("selected_controls") or []
    if selected:
        lines.append("Controls selected by the optimizer, highest reduction first:")
        for c in selected:
            lines.append(
                f"- {c.get('name')}: cost INR {c.get('cost_inr')}, "
                f"modeled EAL reduction INR {c.get('eal_reduction_inr')} "
                f"({c.get('eal_reduction_pct')} of that finding's EAL)."
            )
        lines.append("")

    top = context.get("top_findings") or []
    if top:
        lines.append("Highest-EAL findings in the assessment:")
        for f in top:
            lines.append(
                f"- {f.get('title')} on {f.get('asset_name')}: "
                f"likelihood {f.get('likelihood')}, EAL INR {f.get('eal_inr')}."
            )
        lines.append("")

    totals = context.get("totals") or {}
    if totals:
        lines.append("Totals: " + ", ".join(f"{k} = {v}" for k, v in totals.items()))
        lines.append("")

    lines.append(
        "Modeled estimates based on supplied inputs. "
        "Not a guarantee of actual losses."
    )
    return "\n".join(lines)


@lru_cache(maxsize=1)
def get_bedrock_service() -> BedrockService:
    return BedrockService()
